### ISSUE TITLE
During worker scale up add node model number to the name

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/JetSki#81]
For example the templated out yaml should be like
```
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: worker073-fc640
spec:
  online: true
  bmc:
    address: ipmi://mgmt-<blah>
    credentialsName: worker-073-bmc-secret
  bootMACAddress: 3c:fd:fe:e7:9c:30
```
